# Adapted from https://github.com/HumanBrainProject/openMINDS/blob/871e382/.github/workflows/validate-schemas.yml
# MIT licensed

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: openMINDS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule sync
        git submodule update --init --recursive --remote
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout generator repo
      uses: actions/checkout@v2
      with:
        repository: HumanBrainProject/openMINDS
        ref: generator
        path: generator
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f generator/requirements.txt ]; then pip install -r generator/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run generation
      run: |
        cd core
        python ../generator/openMINDS.py --version v3
        cd ../SANDS
        python ../generator/openMINDS.py --version v1
        cd ../controlledTerms
        python ../generator/openMINDS.py --version v1
        cd ..
        mkdir -p expanded/core/v3
        mkdir -p expanded/SANDS/v1
        mkdir -p expanded/controlledTerms/v1
        mkdir -p target/core/v3
        mkdir -p target/SANDS/v1
        mkdir -p target/controlledTerms/v1
        mv core/expanded/* expanded/core/v3
        mv core/target/* target/core/v3
        mv SANDS/expanded/* expanded/SANDS/v1
        mv SANDS/target/* target/SANDS/v1
        mv controlledTerms/expanded/* expanded/controlledTerms/v1
        mv controlledTerms/target/* target/controlledTerms/v1
        python vocab/vocab_extractor.py
    - name: Archive expanded version
      uses: actions/upload-artifact@v2
      with:
        name: expanded schema templates
        path: |
          expanded
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: target files
        path: |
          target
    - run: |
        git config user.name openMINDS
        git config user.email openMINDS@ebrains.eu
        if [[ $(git add . --dry-run | wc -l) -gt 0 ]]; then           
            git add .
            git commit -m "Automated vocabulary extraction"
            git push
        else
            echo "Nothing to commit"
        fi
